[project]
name = "gradient-decent-showcase"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Zane Willgruber", email = "73185743+ZaneWillgruber@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.5.2",
    "torch>=2.14.0",
]

[project.scripts]
gradient-decent-showcase = "gradient_decent_showcase:main"

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cpu" }

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
